type QuotesList = Array<{ id: number, text: string, author: string }>;

export const arrQuotes: QuotesList = [
  { id: 1, text: 'Help me, Obi-Wan Kenobi. You’re my only hope.', author: 'Leia Organa' },
  { id: 3, text: 'I find your lack of faith disturbing.', author: 'Darth Vader' },
  { id: 4, text: 'The Force will be with you. Always.', author: 'Obi-Wan Kenobi' },
  { id: 5, text: 'Why, you stuck-up, half-witted, scruffy-looking nerf herder!', author: 'Leia Organa' },
  { id: 2, text: 'Never tell me the odds!', author: 'Han Solo' },
  { id: 6, text: 'Do. Or do not. There is no try.', author: 'Yoda' },
  { id: 7, text: 'No. I am your father.', author: 'Darth Vader' },
  { id: 8, text: 'When gone am I, the last of the Jedi will you be. The Force runs strong in your family. Pass on what you have learned.', author: ' Yoda' },
  { id: 8, text: 'I’ll never turn to the dark side. You’ve failed, your highness. I am a Jedi, like my father before me.', author: 'Luke Skywalker' },
  { id: 9, text: 'Now, young Skywalker, you will die.', author: 'Emperor Palpatine' },
  { id: 10, text: 'Just for once, let me look on you with my own eyes.', author: 'Anakin Skywalker' },
  { id: 11, text: 'There’s always a bigger fish.', author: 'Qui-Gon Jinn' },
  { id: 12, text: 'In time, the suffering of your people will persuade you to see our point of view.', author: 'Nute Gunray' },
  { id: 13, text: 'You can’t stop the change, any more than you can stop the suns from setting.', author: 'Shmi Skywalker' },
  { id: 14, text: 'Fear is the path to the dark side. Fear leads to anger; anger leads to hate; hate leads to suffering. I sense much fear in you.', author: 'Yoda' },
  { id: 15, text: 'Well, if droids could think, there’d be none of us here, would there?', author: 'Obi-Wan Kenobi' },
  { id: 16, text: 'We must keep our faith in the Republic. The day we stop believing democracy can work is the day we lose it.', author: 'Queen Jamillia' },
  { id: 17, text: 'I’m just a simple man trying to make my way in the universe.', author: 'Jango Fett' },
  { id: 18, text: 'What if I told you that the Republic was now under the control of a Dark Lord of the Sith?', author: 'Count Dooku' },
  { id: 19, text: 'The dark side of the Force is a pathway to many abilities some consider to be unnatural.', author: 'Chancellor Palpatine' },
  { id: 20, text: 'Power! Unlimited power!', author: 'Darth Sidious' },
  { id: 21, text: 'So this is how liberty dies. With thunderous applause.', author: 'Padmé Amidala' },
  { id: 22, text: 'You were my brother, Anakin. I loved you.', author: 'Obi-Wan Kenobi' },
  { id: 23, text: 'You know, no matter how much we fought, I’ve always hated watching you leave.', author: 'Leia Organa' },
  { id: 24, text: 'Oh, my dear friend. How I’ve missed you.', author: 'C-3PO' },
  { id: 25, text: 'I’m one with the Force. The Force is with me.', author: 'Chirrut Îmwe' },
  { id: 26, text: 'Jyn, I’ll be there for you. Cassian said I had to.', author: 'K-2SO' },
  { id: 27, text: 'Hope.', author: 'Leia Organa' },
  { id: 28, text: 'Fear is the path to the dark side…fear leads to anger…anger leads to hate…hate leads to suffering', author: 'Yoda' },
  { id: 29, text: 'Rrwwwgg Ggwwwrghh Rawrgwawggr Rrraarrwhhgwwr', author: 'Chewbacca' },
  { id: 30, text: 'Chewie, we’re home.', author: 'Han Solo' }
];

